application: incognito-site
version: 1
runtime: python
api_version: 1

derived_file_type:
- python_precompiled

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /img
  static_dir: img
- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img
- url: .*
  script: main.py
