application: incognito-site-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: true

derived_file_type:
- python_precompiled

libraries:
- name: ssl
  version: latest

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /img
  static_dir: img
- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img
- url: /.*
  script: incognito.app